name: Build macOS app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated from v2 to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app

      - name: Build the macOS app
        run: |
          python setup.py py2app

      - name: Archive build output
        uses: actions/upload-artifact@v3  # Ensure you’re using the latest version (v3)
        with:
          name: macOS App
          path: dist/*.app
