name: Build macOS app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to latest version
        with:
          python-version: '3.x'

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: |
          pip install py2app

      - name: Build the macOS app
        run: |
          python setup.py py2app
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning

      - name: Archive build output
        uses: actions/upload-artifact@v3  # Latest version
        with:
          name: macOS App
          path: dist/*.app
